image: node:8

cache:
  paths:
  - node_modules

build:
  script:
  - yarn
  - yarn build
  - cd build/
  - mv css/ images/ scripts/ Model.php hooks.php ../
  - cd ../
  artifacts:
    paths:
    - css/
    - images/
    - scripts/
    - Model.php
    - hooks.php
