language: node_js

node_js:
  - "6"

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run build

before_deploy:
  - cd build/
  - zip -r camera-slider *

deploy:
  provider: releases
  api_key:
    secure: JffJyt6+wstrzHRDPrgg+r8SoAM1+mCBUrPZvJ59wQlTCpi8usoWrDx+vnuQpWfJmHBCWsmcvydOtD6CJXilk+nt2z2d/TBdjoOv6uq0+ZmjAGdSdl9X+KdLevuNJLswfSV8o5VWRo+xyCRy5jc0uBNrZ2l/Vwab+hPrhoqdARjBqRpF0gd0XjEJyU0bHgNoQVPo0sh0zqGpElK2vXT8P/bJY3lBQtqN/D04qZeV+CNFgWSoeTJsLw4XV5+GUAfIBHyY+5/gmYQKSAq2qIb1MKlZCwGyKdIywd4HDA+otPl+IXz3sqoS3Cvdl8k3GY+wlmflRIU/SUlu07vX9cVo6dhrzrBCpCbKAsSoyTAPPoHUhkLzMYuF0B2MWLkLFPalgT7MTGSa+0TG0CS2mvpDZPidAi8qcim4+j4MEKL2oabVZogE35T2PoSq96eiWsU+fTs6UuTl3VggAyJK4BhwMOQ1Bnrz4oKsH2sQQfUEljFkMAy558AhDe2/Hu+WlOoyuuum60LEr9hchSDpyw2m5fGsS9/Lo3Q44mL3bai4iRn2d76lwgiBI9iuNNsQ1JK9VwGAdJcSwp9jbChD+hGDQx3gcyGycg7GZMac7/+Zc+qpTslc7/AApKcxXFvM/pBk7fqE9eNI6X90NrL8U05ggRH/sAUCF7SF9rvyyG3KXAk=
  file: camera-slider.zip
  on:
    tags: true
