language: node_js

node_js:
  - "6"

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run build

before_deploy:
  - cd build/
  - zip -r camera-slider *

deploy:
  provider: releases
  api_key:
    secure: fDFhJLYJglBrtUdMD++Yj7IVkWBnT9SSDGbqWwNcRDGiXaCsv2DfVCVC2W3wixwBdxS8ojAq3WmtElYpLSa82QraViI2ZCgGEFc4tjGg3CF+Wg4R9pg5pmlUcyD2dGhvyhBFv7aIEsmWQlitoFGYBWSPVA3LEYyLfk/5zB75dq4PmWrdO24p0ruL/L/7Qe4yJnhTwn2iHEIa9kgiRN1ULGYMx8TDomXqlvnn/Z9Y1qxZabx7dvdraCnOtwzXXNAN+hsCD+YlKB5iSQZQ2KVqyk86X2mfY5nZk/tkY65iH0GVFledBX9ADUQ8pGAjAC1IdAnP47JiJbzi3VC3P6Lf7yK//4bzvjfe/CNqmcHCJZvs5u+LhU0FdrBOYcEyOLzYbp3fn+0f6Q3w9NnthFmT334QsDctUZy9730TXIBUS5P+rtKweD2wqq76KcC7fkqlvIWARlaCj8xavyaPhMVJyJZnU0lNSjm5jFzrwOoyL3TNemu75+fvgllfQNUArESp6oIi3CbVpKm8DhFstwZiLTaW+Oy3tg/vbQ5D4YP2sAKm1irOv9fAGgWLhm+kHTLxwW9LJjFTHipAsmSY+YMAnTt0QrzHx3mvwrPcwdxT2NpN3fT/yB3+IcGVuLz6fllitS77F1+mXAOCsyjnHrl6gSKYhxkkk2RILRvO4KYsNa0=
  file: camera-slider.zip
  on:
    tags: true
